SELECT DECODE(TRUNC(GRADE/8),1, NAME, NULL), GRADE, MARKS
FROM (
SELECT NAME, GRADE, MARKS
FROM STUDENTS, GRADES
WHERE STUDENTS.MARKS BETWEEN GRADES.MIN_MARK and GRADES.MAX_MARK)
ORDER BY GRADE DESC, NAME, MARKS;