SELECT HACKER_ID, NAME
FROM (
SELECT D.HACKER_ID AS HACKER_ID, E.NAME AS NAME, COUNT(D.SCORE) AS COUNT
FROM (
SELECT A.HACKER_ID, A.SCORE, C.SCORE AS FULL_SCORE
FROM SUBMISSIONS A INNER JOIN CHALLENGES B
ON A.CHALLENGE_ID = B.CHALLENGE_ID
INNER JOIN DIFFICULTY C
ON B.DIFFICULTY_LEVEL = C.DIFFICULTY_LEVEL) D
INNER JOIN HACKERS E
ON D.HACKER_ID = E.HACKER_ID
WHERE D.SCORE = D.FULL_SCORE
GROUP BY D.HACKER_ID, E.NAME
ORDER BY COUNT DESC, HACKER_ID)
WHERE COUNT > 1;